apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-app
  name: sample-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: sample-app
          image: amankinenko/sample-app-1:01f7fc0
